spring:
  profiles: local
  redis:
    host: 127.0.0.1
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456

---

spring:
  profiles: k8s
  redis:
    host: redis
    password: IdxTCbD3bL%
  datasource:
    url: jdbc:mysql://mysql:3306/test?useSSL=false
    username: root
    password: 6wqMG01XK1