spring:
  profiles: local
  redis:
    host: 127.0.0.1
host:
  sample:
    api: "127.0.0.1:9527"

---

spring:
  profiles: k8s
  redis:
    host: redis
    password: A8xOL6Dmmh%
host:
  sample:
    api: "sample-api"