version: '3'

services:
#  sample-task:
#    image: jianminhuang/sample-task:latest
#    environment:
#      - TZ=Asia/Taipei
#      - activeProfiles=local
#    networks:
#      - default
#  sample-api:
#    image: jianminhuang/sample-api:latest
#    expose:
#      - 9527
#    ports:
#      - 9527:9527
#    environment:
#      - TZ=Asia/Taipei
#      - activeProfiles=local
#    networks:
#      - default
  redis:
    image: sameersbn/redis:4.0.9-3
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - default
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - default
#  oracle:
#    image: oracleinanutshell/oracle-xe-11g:latest
#    expose:
#      - 1521
#    ports:
#      - 1521:1521
#    networks:
#      - default

networks:
  default:
